### ISSUE TITLE
Inquiry Regarding Long Dependency Score Results

### ISSUE THREAD

**Issue by ZackZikaiXiao** [October2001/ProLong#1]
Thank you for your hard work. The long dependency score is a fascinating metric that reveals the characteristics of long text data.

I have converted [LongAlpaca-12k](https://huggingface.co/datasets/Yukang/LongAlpaca-12k) into the format you provided:
`{"text": "This is the first sentence. This is the second sentence. This is the third sentence."}`

I ran the `run_batch_multi_process.py script`, but most of the data in prolong/results/merged/scores.txt **have a score of 0.** Could you please let me know if this is expected behavior?

Thank you for your assistance.

**Comment by October2001** [comment]
Thank you for your interest in ProLong!

**Comment by October2001** [comment]
Thank you for your interest in ProLong! 

The issue you've described should occur because  `sample_size` > `len(pairs)`, hence the $\Delta ppl$ was not calculated. Therefore, you could try reducing the  `sample_size`, or simply set the `sample_size` to `-1` to skip the sampling altogether.

Additionally, to ensure a fair selection process, we hope that the data you use for filtering should be preprocessed to have approximately the same length. Otherwise, the longer data entries are more likely to obtain higher LDS.

**Comment by ZackZikaiXiao** [comment]
Thanks for your response and kind reminder. I'll reset the sample_size and try again. Besides, I have no idea about extending data to approximately the same length. Have you constructed a same-length supervised finetune dataset from English books and code data? I searched for some long context SFT datasets and found that almost all of them exhibit length imbalance, especially with short texts being far more prevalent than long texts.
